### ISSUE TITLE
Will not compile on Windows 10

### ISSUE THREAD

**Issue by caecos** [azrrik/az-vcv#1]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Modulo.cpp.o src/Modulo.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
g++ -o plugin.dll build/src/Modulo.cpp.o build/src/plugin.cpp.o -shared -LC:/msys64/Rack-SDK -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/src/plugin.cpp.o:plugin.cpp:(.rdata$.refptr.modelCompare[.refptr.modelCompare]+0x0): undefined reference to `modelCompare'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/Rack-SDK/compile.mk:59 : plugin.dll] Erreur 1

**Comment by azrrik** [comment]
I removed the reference.  Can you try again?

**Comment by caecos** [comment]
In order to compile, one must download the master file and decompress it. Fine module...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : azrrik <notifications@github.com>
Envoyé : Sunday, May 10, 2020 10:58:44 PM
À : azrrik/az-vcv <az-vcv@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [azrrik/az-vcv] Will not compile on Windows 10 (#1)


I removed the reference. Can you try again?
