### ISSUE TITLE
Will not compile on Windows 10 using MSYS2

### ISSUE THREAD

**Issue by caecos** [azrrik/az-vcv#2]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Agent.cpp.o src/Agent.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/LoFiTV.cpp.o src/LoFiTV.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Modulo.cpp.o src/Modulo.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Slime.cpp.o src/Slime.cpp
src/Slime.cpp: In member function 'void Slime::reset(int, float, float, float)':
src/Slime.cpp:41:7: error: 'uint' was not declared in this scope; did you mean 'rint'?
   41 |  for (uint i = 0; i < trailMap.size(); ++i) {
      |       ^~~~
      |       rint
src/Slime.cpp:41:19: error: 'i' was not declared in this scope
   41 |  for (uint i = 0; i < trailMap.size(); ++i) {
      |                   ^
src/Slime.cpp:42:11: error: expected ';' before 'j'
   42 |   for(uint j = 0; j < trailMap[i].size(); ++j) {
      |           ^~
      |           ;
src/Slime.cpp:42:19: error: 'j' was not declared in this scope
   42 |   for(uint j = 0; j < trailMap[i].size(); ++j) {
      |                   ^
make: *** [C:/msys64/Rack-SDK/compile.mk:69 : build/src/Slime.cpp.o] Erreur 1

**Comment by azrrik** [comment]
Thanks for the bug report.  I've pushed a fix for this.  Apparently, the uint type doesn't exist in windows but it does in linux... odd.
