### ISSUE TITLE
feature request: "lights off" compatibility

### ISSUE THREAD

**Issue by davephillips** [azrrik/az-vcv#3]
Greetings ! I've been enjoying the LoFiTV module, thank you for sharing it. I think it's a great candidate for Omri Cohen's "lights off" mode, i.e. everything but the graphics display fades to black. I've got some interesting displays going on, it would be cool to watch them against a darkened background and room lights turned off. 

Omri posted a demonstration video on YT:

https://www.youtube.com/watch?v=X5BwOXiEqrI&ab_channel=OmriCohen

Thanks again for the plugin ! :)

dp

**Comment by azrrik** [comment]
Heya!  Thanks for the feedback!  I'm glad to hear you're enjoying the plugin.

I had no idea it didn't work with the "lights off" plugin.  I completely agree that it would be a lot cooler if it did...  I'll look into it making them compatible.

**Comment by davephillips** [comment]
Hey, nice work on the lights-off support ! Works perfectly here (Ubuntu 18.04, VCV Rack v1.dev), adds much fun. :)

**Comment by azrrik** [comment]
Awesome!  Thanks for testing the change.  There's some occasional tearing because I can't use a Framebuffer due to the way lights off works.  But I like that it gives it a CRT type effect.
