### ISSUE TITLE
high CPU usage with Lofi TV

### ISSUE THREAD

**Issue by davephillips** [azrrik/az-vcv#6]
I love the Lofi TV module but it hits the CPU dramatically. Adding it to a patch drove the peak usage from around 70% to more than 130%. Yikes. Any optimizations that might help lower that consumption rate ?

Best regards,

Dave Phillips

**Comment by azrrik** [comment]
Thanks for the feedback.  I'm glad that you enjoy the module.  I forgot about this bug.  Sorry about the delayed response.

Unfortunately, this is a computationally intensive simulation.  I don't see any low hanging fruit to optimize.  (In fact, I wonder if something this computationally intense is a good fit for a VCV plugin in the first place...  Most other simulations of this type are offloaded to the GPU as a shader.)  

If you want to make some optimizations and submit a pull request, feel free.
